//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.QuestionOptions = new HashSet<QuestionOption>();
            this.RecordDetails = new HashSet<RecordDetail>();
        }
    
        public int QuestionID { get; set; }
        public string QuestionName { get; set; }
        public string Type { get; set; }
        public int ServiceID { get; set; }
        public int Required { get; set; }
        public Nullable<int> Order { get; set; }
        public string TextType { get; set; }
        public int Min { get; set; }
        public int Max { get; set; }
    
        public virtual ServiceItem ServiceItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionOption> QuestionOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordDetail> RecordDetails { get; set; }
    }
}
