//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecordDetail()
        {
            this.RecordDetailsOptions = new HashSet<RecordDetailsOption>();
        }
    
        public int AnswerID { get; set; }
        public int QuestionID { get; set; }
        public string TextAnswer { get; set; }
        public int RecordID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Record Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordDetailsOption> RecordDetailsOptions { get; set; }
    }
}
